import type { OxlintConfig } from 'oxlint';

// Package specifier instead of a relative path: Oxlint rejects relative JS plugin
// paths in configs loaded through `extends`
const PLUGIN_SPECIFIER = '@jmlweb/oxlint-config-base/plugin';

/** Oxlint equivalents of ESLint's `recommended` rules */
const javascriptRules: NonNullable<OxlintConfig['rules']> = {
  'eslint/constructor-super': 'error',
  'eslint/for-direction': 'error',
  'eslint/getter-return': 'error',
  'eslint/no-async-promise-executor': 'error',
  'eslint/no-case-declarations': 'error',
  'eslint/no-class-assign': 'error',
  'eslint/no-compare-neg-zero': 'error',
  'eslint/no-cond-assign': 'error',
  'eslint/no-const-assign': 'error',
  'eslint/no-constant-binary-expression': 'error',
  'eslint/no-constant-condition': 'error',
  'eslint/no-control-regex': 'error',
  'eslint/no-debugger': 'error',
  'eslint/no-delete-var': 'error',
  'eslint/no-dupe-class-members': 'error',
  'eslint/no-dupe-else-if': 'error',
  'eslint/no-dupe-keys': 'error',
  'eslint/no-duplicate-case': 'error',
  'eslint/no-empty': 'error',
  'eslint/no-empty-character-class': 'error',
  'eslint/no-empty-pattern': 'error',
  'eslint/no-empty-static-block': 'error',
  'eslint/no-ex-assign': 'error',
  'eslint/no-extra-boolean-cast': 'error',
  'eslint/no-fallthrough': 'error',
  'eslint/no-func-assign': 'error',
  'eslint/no-global-assign': 'error',
  'eslint/no-import-assign': 'error',
  'eslint/no-invalid-regexp': 'error',
  'eslint/no-irregular-whitespace': 'error',
  'eslint/no-loss-of-precision': 'error',
  'eslint/no-misleading-character-class': 'error',
  'eslint/no-new-native-nonconstructor': 'error',
  'eslint/no-nonoctal-decimal-escape': 'error',
  'eslint/no-obj-calls': 'error',
  'eslint/no-prototype-builtins': 'error',
  'eslint/no-redeclare': 'error',
  'eslint/no-regex-spaces': 'error',
  'eslint/no-self-assign': 'error',
  'eslint/no-setter-return': 'error',
  'eslint/no-shadow-restricted-names': 'error',
  'eslint/no-sparse-arrays': 'error',
  'eslint/no-this-before-super': 'error',
  'eslint/no-unassigned-vars': 'error',
  'eslint/no-undef': 'error',
  'eslint/no-unexpected-multiline': 'error',
  'eslint/no-unreachable': 'error',
  'eslint/no-unsafe-finally': 'error',
  'eslint/no-unsafe-negation': 'error',
  'eslint/no-unsafe-optional-chaining': 'error',
  'eslint/no-unused-labels': 'error',
  'eslint/no-unused-private-class-members': 'error',
  'eslint/no-unused-vars': 'error',
  'eslint/no-useless-assignment': 'error',
  'eslint/no-useless-backreference': 'error',
  'eslint/no-useless-catch': 'error',
  'eslint/no-useless-escape': 'error',
  'eslint/no-with': 'error',
  'eslint/preserve-caught-error': 'error',
  'eslint/require-yield': 'error',
  'eslint/use-isnan': 'error',
  'eslint/valid-typeof': 'error',
};

/** Core rules the TypeScript compiler already enforces, as in typescript-eslint's `eslint-recommended` */
const compilerCheckedRules: NonNullable<OxlintConfig['rules']> = {
  'eslint/constructor-super': 'off',
  'eslint/getter-return': 'off',
  'eslint/no-class-assign': 'off',
  'eslint/no-const-assign': 'off',
  'eslint/no-dupe-class-members': 'off',
  'eslint/no-dupe-keys': 'off',
  'eslint/no-func-assign': 'off',
  'eslint/no-import-assign': 'off',
  'eslint/no-new-native-nonconstructor': 'off',
  'eslint/no-obj-calls': 'off',
  'eslint/no-redeclare': 'off',
  'eslint/no-setter-return': 'off',
  'eslint/no-this-before-super': 'off',
  'eslint/no-undef': 'off',
  'eslint/no-unreachable': 'off',
  'eslint/no-unsafe-negation': 'off',
  'eslint/no-with': 'off',
  'eslint/no-implied-eval': 'off',
  'eslint/no-throw-literal': 'off',
  'eslint/prefer-promise-reject-errors': 'off',
  'eslint/require-await': 'off',
};

/** Syntax-only rules from typescript-eslint's `recommended`, `strict` and `stylistic` presets */
const typescriptRules: NonNullable<OxlintConfig['rules']> = {
  'typescript/ban-ts-comment': ['error', { minimumDescriptionLength: 10 }],
  'eslint/no-array-constructor': 'error',
  'typescript/no-duplicate-enum-values': 'error',
  'typescript/no-empty-object-type': 'error',
  'typescript/no-explicit-any': 'error',
  'typescript/no-extra-non-null-assertion': 'error',
  'typescript/no-misused-new': 'error',
  'typescript/no-namespace': 'error',
  'typescript/no-non-null-asserted-optional-chain': 'error',
  'typescript/no-require-imports': 'error',
  'typescript/no-this-alias': 'error',
  'typescript/no-unnecessary-type-constraint': 'error',
  'typescript/no-unsafe-declaration-merging': 'error',
  'typescript/no-unsafe-function-type': 'error',
  'eslint/no-unused-expressions': 'error',
  'eslint/no-unused-vars': 'error',
  'typescript/no-wrapper-object-types': 'error',
  'typescript/prefer-as-const': 'error',
  'typescript/prefer-namespace-keyword': 'error',
  'typescript/triple-slash-reference': 'error',
  'typescript/no-dynamic-delete': 'error',
  'typescript/no-extraneous-class': 'error',
  'typescript/no-invalid-void-type': 'error',
  'typescript/no-non-null-asserted-nullish-coalescing': 'error',
  'typescript/no-non-null-assertion': 'error',
  'eslint/no-useless-constructor': 'error',
  'typescript/prefer-literal-enum-member': 'error',
  'typescript/unified-signatures': 'error',
  'typescript/adjacent-overload-signatures': 'error',
  'typescript/array-type': 'error',
  'typescript/ban-tslint-comment': 'error',
  'typescript/class-literal-property-style': 'error',
  'typescript/consistent-generic-constructors': 'error',
  'typescript/consistent-indexed-object-style': 'error',
  'typescript/consistent-type-assertions': 'error',
  'typescript/consistent-type-definitions': 'error',
  'typescript/no-confusing-non-null-assertion': 'error',
  'eslint/no-empty-function': 'error',
  'typescript/no-inferrable-types': 'error',
  'typescript/prefer-for-of': 'error',
  'typescript/prefer-function-type': 'error',
};

/**
 * Rules from typescript-eslint's `strict-type-checked` and `stylistic-type-checked` presets.
 * They only run when the consumer enables `options.typeAware`
 */
const typeAwareRules: NonNullable<OxlintConfig['rules']> = {
  'typescript/await-thenable': 'error',
  'typescript/no-array-delete': 'error',
  'typescript/no-base-to-string': 'error',
  'typescript/no-confusing-void-expression': 'error',
  'typescript/no-deprecated': 'error',
  'typescript/no-duplicate-type-constituents': 'error',
  'typescript/no-floating-promises': 'error',
  'typescript/no-for-in-array': 'error',
  'typescript/no-generated-empty-object-type': 'error',
  'typescript/no-implied-eval': 'error',
  'typescript/no-meaningless-void-operator': 'error',
  'typescript/no-misused-promises': 'error',
  'typescript/no-misused-spread': 'error',
  'typescript/no-mixed-enums': 'error',
  'typescript/no-redundant-type-constituents': 'error',
  'typescript/no-unnecessary-boolean-literal-compare': 'error',
  'typescript/no-unnecessary-condition': 'error',
  'typescript/no-unnecessary-template-expression': 'error',
  'typescript/no-unnecessary-type-arguments': 'error',
  'typescript/no-unnecessary-type-assertion': 'error',
  'typescript/no-unnecessary-type-conversion': 'error',
  'typescript/no-unnecessary-type-parameters': 'error',
  'typescript/no-unsafe-argument': 'error',
  'typescript/no-unsafe-assignment': 'error',
  'typescript/no-unsafe-call': 'error',
  'typescript/no-unsafe-enum-comparison': 'error',
  'typescript/no-unsafe-member-access': 'error',
  'typescript/no-unsafe-return': 'error',
  'typescript/no-unsafe-unary-minus': 'error',
  'typescript/no-useless-default-assignment': 'error',
  'typescript/only-throw-error': 'error',
  'typescript/prefer-promise-reject-errors': 'error',
  'typescript/prefer-reduce-type-parameter': 'error',
  'typescript/prefer-return-this-type': 'error',
  'typescript/related-getter-setter-pairs': 'error',
  'typescript/require-await': 'error',
  'typescript/restrict-plus-operands': [
    'error',
    {
      allowAny: false,
      allowBoolean: false,
      allowNullish: false,
      allowNumberAndString: false,
      allowRegExp: false,
    },
  ],
  'typescript/restrict-template-expressions': [
    'error',
    {
      allowAny: false,
      allowBoolean: false,
      allowNever: false,
      allowNullish: false,
      allowNumber: false,
      allowRegExp: false,
    },
  ],
  'typescript/return-await': ['error', 'error-handling-correctness-only'],
  'typescript/unbound-method': 'error',
  'typescript/use-unknown-in-catch-callback-variable': 'error',
  'typescript/dot-notation': 'error',
  'typescript/non-nullable-type-assertion-style': 'error',
  'typescript/prefer-find': 'error',
  'typescript/prefer-includes': 'error',
  'typescript/prefer-nullish-coalescing': 'error',
  'typescript/prefer-optional-chain': 'error',
  'typescript/prefer-regexp-exec': 'error',
  'typescript/prefer-string-starts-ends-with': 'error',
};

/**
 * Base Oxlint configuration for JavaScript and TypeScript projects.
 * Mirrors @jmlweb/eslint-config-base-js for JavaScript files and
 * @jmlweb/eslint-config-base for TypeScript files.
 */
const config: OxlintConfig = {
  plugins: ['typescript', 'import'],
  jsPlugins: [PLUGIN_SPECIFIER],
  categories: {
    correctness: 'error',
  },
  rules: javascriptRules,
  overrides: [
    {
      files: ['**/*.{ts,tsx,mts,cts}'],
      rules: {
        ...compilerCheckedRules,
        ...typescriptRules,
        ...typeAwareRules,
        'typescript/no-explicit-any': 'error',
        'eslint/no-unused-vars': [
          'error',
          { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
        ],
        'typescript/consistent-type-imports': [
          'error',
          { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
        ],
        'typescript/consistent-type-definitions': ['error', 'type'],
        'typescript/no-require-imports': 'error',
        // Prefer const maps over enums
        'jmlweb/no-enum': 'error',
        // Encourage immutability
        'eslint/no-param-reassign': ['error', { props: true }],
        // Named exports only
        'import/no-default-export': 'error',
      },
    },
    {
      // Tool config files must default-export their configuration
      files: ['**/*.config.{ts,mts,cts}'],
      rules: {
        'import/no-default-export': 'off',
      },
    },
  ],
};

export default config;
